[package]
name = "arizyen/math-cannon-battle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Signal = "sleitnick/signal@2.0.1"
Flipper = "reselim/flipper@2.0.0"
# roact-spring = "chriscerie/roact-spring@2.0.0"
# RoactFlipper = "reselim/roact-flipper@2.0.0"
# Llama = "freddylist/llama@1.1.1"
Sift = "csqrl/sift@0.0.9"
Promise = "evaera/promise@4.0.0"
# Roact = "roblox/roact@1.4.4"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Rodux = "roblox/rodux@3.0.0"
ReactRedux = "chriscerie/react-redux@0.1.0"
# RoactRodux = "roblox/roact-rodux@0.3.0"
# Janitor = "howmanysmall/janitor@1.13.15"
# RbxCameraShaker = "sleitnick/RbxCameraShaker""
RoSelect = "rimuy/roselect@0.1.3"
t = "osyrisrblx/t@3.1.1"
